### ISSUE TITLE
consider using package:code_builder for this repo

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/web#11]
I haven't looked too closely at how the Dart code is generated, but from the imports it looks like we're not using `package:code_builder`. We might consider doing that; some advantages would be:

- it's got a readable api for generating code
- it can do things like intelligently handle which imports to write for a generated file, based on the symbols used in that file
- any improvements we need to make to `code_builder` to support this generator will likely be generally useful for other consumers of that library

**Comment by joshualitt** [comment]
Great suggestion, this works perfectly for our use cases so far. As we iterate we may need more functionality from `code_builder`, but I agree it makes sense to improve `code_builder` vs manipulate strings.
