### ISSUE TITLE
Add documentation for types and their members

### ISSUE THREAD

**Issue by srujzs** [dart-lang/web#122]
We should likely fetch data from the MDN and auto-annotate IDL types.

**Comment by devoncarew** [comment]
The data from the `web-features` npm package looks like a better source of feature info than the `web-specs` one I started pulling from (https://github.com/dart-lang/web/pull/111).

**Comment by devoncarew** [comment]
This is mostly done; we can track remaining work / improvements in more specific issues (eg. https://github.com/dart-lang/web/issues/190).
