### ISSUE TITLE
dart:js_interop is not visible in flutter

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/web#14]
This may be more of an FYI, but when opening this repo with VS Code - when configured to use a Dart SDK from the Flutter SDK - the JS* types don't resolve (JSPromise, JSObject, JSVoid, JSArray, ...). I assume these all come from the `dart:js_interop` library?

The analysis issues clear up when I switch to using a non-Flutter Dart SDK. Is the `dart:js_interop` library newer? Are these issues expected (i.e. has the `dart:js_interop` library not been contributed to Flutter?)?

**Comment by kevmoo** [comment]
Does Flutter need to explicitly opt-in to every Dart library it wants?

**Comment by joshualitt** [comment]
I think we have to update some files on the engine side to copy over `dart:js_interop` into their built version of the SDK.  I can deal with this when I update the engine shim to use JS types.

**Comment by devoncarew** [comment]
Adding it to flutter would raise the visibility of the API - it would likely start to show up at api.flutter.dev. When do we want this API to appear in our own docs by default? I notice that it doesn't yet show up in our beta docs: https://api.dart.dev/beta/3.0.0-218.1.beta/index.html.

Re: adding it to flutter, it might involve edits in a few places? But at least for analysis, I believe the file(s) you need to update are here: https://github.com/flutter/engine/tree/main/sky/packages/sky_engine.

**Comment by joshualitt** [comment]
RE: Documentation, I'm not really sure. I think we're going to start trying to document things starting next month.

RE: Adding it to Flutter, yea, I think there are at least two GN files I need to update. This has become a higher priority recently. However, I need https://dart-review.googlesource.com/c/sdk/+/284491 to land in the SDK and roll into the engine, and then hopefully I can expose the library through the sky package.

**Comment by kevmoo** [comment]
The CL above landed. Do we need to hack on flutter now?

**Comment by kevmoo** [comment]
This issue should really be on flutter/flutter now, right?

**Comment by joshualitt** [comment]
I think this might be working, I seem to be able to use `dart:js_interop` in plugins, for example. If we need something else here we should file a bug and fix it on the Flutter side.
