### ISSUE TITLE
WebSocket protocols is an array of string not JSAny[]

### ISSUE THREAD

**Issue by konsultaner** [dart-lang/web#182]
I wanted to start using this package in favour of the dart:html package. So I'm not sure if this is intentional, but

https://github.com/dart-lang/web/blob/975e55cbe4ac683c33d5256a91f4133fa97b4c34/lib/src/dom/websockets.dart#L19

should by of type String. According to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket#protocols):

> Either a single protocol string or an array of protocol strings. These strings are used to indicate sub-protocols, so that a single server can implement multiple WebSocket sub-protocols (for example, you might want one server to be able to handle different types of interactions depending on the specified protocol).

How do I use JSAny from a String anyway? How can I cast or wrap or transform it into a JSAny?

**Comment by kevmoo** [comment]
Use `JSString` - https://api.dart.dev/stable/3.3.0/dart-js_interop/JSString-extension-type.html

You can do `'My Dart String'.toJS`

**Comment by konsultaner** [comment]
and why not use <String>[] instead? can I also do this:

    _socket = WebSocket(_url, [_serializerType].toJSBox);

or 

    _socket = WebSocket(_url, [_serializerType] as JSAny);

?

**Comment by kevmoo** [comment]
```_socket = WebSocket(_url, [_serializerType] as JSAny);`

May work fine in `dart2js` but will almost certainly fail in `dart2wasm`.

**Comment by konsultaner** [comment]
_socket = WebSocket(_url, [_serializerType].toJSBox);

this is ok?

is there a way to do something like `JSON.stringify()`? I got an error Event which is just a DOM Event and I can't get the actual error.
