### ISSUE TITLE
Question: how to make a http query using this library?

### ISSUE THREAD

**Issue by alexkmbk** [dart-lang/web#186]
I wonder if it is possible to make an HTTP request (POST, GET...) only in a pure webassembly compatible way, without using the http library? Or maybe there is a plan to make the http library webassembly compatible too?

**Comment by kevmoo** [comment]
https://github.com/dart-lang/web/blob/main/lib/src/helpers/http.dart

It's all there with some helpers. We are likely going to remove the helpers, but you can use that code as inspiration!

**Comment by alexkmbk** [comment]
> https://github.com/dart-lang/web/blob/main/lib/src/helpers/http.dart
> 
> It's all there with some helpers. We are likely going to remove the helpers, but you can use that code as inspiration!

Thank you! I thought the http library is not compatible with wasm.

**Comment by kevmoo** [comment]
@alexkmbk – it IS! It's been migrated. Works great.
