### ISSUE TITLE
Dictionary constructors do not contain parameters from the supertype's constructor

### ISSUE THREAD

**Issue by ditman** [dart-lang/web#188]
The `FilePropertyBag` [constructor](https://github.com/dart-lang/web/blob/main/lib/src/dom/fileapi.dart#L60) only accepts the `lastModified` property, however since it extends `BlobPropertyBag`, it should also [support](https://github.com/dart-lang/web/blob/main/lib/src/dom/fileapi.dart#L37-L40) (and "pass through"[^1]) `type` and `endings` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/File/File#options))

Is there any way of expressing this in the generated code, or does this need a specific helper?

[^1]: This pass-through is probably a noop, there's no need to call the super constructor for this in JS, it's just that these PropertyBags should merge all the constructor arguments as you go down the inheritance chain?

**Comment by kevmoo** [comment]
CC @srujzs

**Comment by srujzs** [comment]
Ah, it looks like we're not handling dictionary inheritance properly:

https://webidl.spec.whatwg.org/#dfn-dictionary

> A given dictionary value of type D can have [entries](https://infra.spec.whatwg.org/#map-entry) for each of the dictionary members defined on D and on any of D’s [inherited dictionaries](https://webidl.spec.whatwg.org/#dfn-inherited-dictionaries).

I'll modify the title to be more general. We likely want to prioritize this.

**Comment by srujzs** [comment]
Hmm, I'm thinking about this a bit more and not quite sure what the right answer is. An example where this might be a bad idea is `DragEventInit`. `DragEventInit` is a subtype of `MouseEventInit`, `EventModifierInit`, `UIEventInit`, and `EventInit`: https://github.com/w3c/webref/blob/ac13138cc839f523975fe4308495329d36a8a578/ed/idl/html.idl#L1767.

But `DragEvent` only cares about the one member `DragEventInit` exposes: https://developer.mozilla.org/en-US/docs/Web/API/DragEvent/DragEvent, so we end up exposing a constructor with tens of members that are all irrelevant. This may be okay as long as none of the supertypes' members are required, but it looks very confusing:

```dart
  external factory DragEventInit({
    bool bubbles,
    bool cancelable,
    bool composed,
    Window? view,
    int detail,
    int which,
    bool ctrlKey,
    bool shiftKey,
    bool altKey,
    bool metaKey,
    bool modifierAltGraph,
    bool modifierCapsLock,
    bool modifierFn,
    bool modifierFnLock,
    bool modifierHyper,
    bool modifierNumLock,
    bool modifierScrollLock,
    bool modifierSuper,
    bool modifierSymbol,
    bool modifierSymbolLock,
    int screenX,
    int screenY,
    int clientX,
    int clientY,
    int button,
    int buttons,
    EventTarget? relatedTarget,
    DataTransfer? dataTransfer,
  });
```
