### ISSUE TITLE
Navigator.deviceMemory is missing

### ISSUE THREAD

**Issue by miquelbeltran** [dart-lang/web#192]
Hello team,

I am working on the migration of `device_info_plus` to `web` package, and noticed that one of the properties we access to is missing.

In this case, is the `deviceMemory` from the `Navigator` in `lib/src/dom/html.dart`.

This property existed in `dart:html`.

References:

- https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory
- https://api.dart.dev/stable/3.3.0/dart-html/Navigator/deviceMemory.html
- https://github.com/fluttercommunity/plus_plugins/issues/2601
- https://github.com/fluttercommunity/plus_plugins/pull/2624

**Comment by srujzs** [comment]
This was removed as part of https://github.com/dart-lang/web/commit/3f1285e9460c2e4141f9a8c2fdca8a0e8af05fa0. We proactively removed a number of APIs that are not fully supported (here, `deviceMemory` is unavailable on Firefox) to reduce the potential for breaking changes as we update IDL version.

However, this was on the more conservative side. We're working on instead requiring that APIs not be experimental and be on the standards track, which `deviceMemory` qualifies: https://github.com/mdn/browser-compat-data/blob/74d447919cd975e16b7f2108d995549dd567d50c/api/Navigator.json#L899. So, it should be added back in a future release soon.

That being said, it's easy to workaround missing APIs by declaring your own member in the meantime e.g.

```dart
extension on Navigator {
  external double get deviceMemory;
}
```

**Comment by miquelbeltran** [comment]
Thanks a lot for the response! Meanwhile, I'll try the extension method.

**Comment by srujzs** [comment]
This hasn't been added yet, but deduping as part of https://github.com/dart-lang/web/issues/209.
