### ISSUE TITLE
requestVideoFrameCallback is missing from HTMLVideoElement

### ISSUE THREAD

**Issue by jezell** [dart-lang/web#203]
https://wicg.github.io/video-rvfc/

https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/requestVideoFrameCallback

**Comment by jezell** [comment]
Corresponding cancellation function also missing:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/cancelVideoFrameCallback

**Comment by srujzs** [comment]
Both should be added as part of https://github.com/dart-lang/web/issues/209, so deduping.
