### ISSUE TITLE
Migration file_picker to WASM support

### ISSUE THREAD

**Issue by amrgetment** [dart-lang/web#212]
I want to compile my app to WASM but I found that I need to migrate several libraries to WASM

```
Context: The unavailable library 'dart:html' is imported through these packages:

    web_plugin_registrant.dart => package:file_picker => dart:html
    web_plugin_registrant.dart => package:flutter_keyboard_visibility_web => dart:html
    web_plugin_registrant.dart => package:fluttertoast => dart:html
    web_plugin_registrant.dart => package:permission_handler_html => dart:html
    web_plugin_registrant.dart => package:share_plus => dart:html
```

So I started by migrating file_picker library
I don't know if here is the right place for asking support
I made the initial migration but I got two cases which I don't know how to migrate

Case 1:
` _target.children.clear();`

Case 2:
` await reader.onLoad.first;`

I wonder how to migrate these two cases
My commit after the initial attempt to migration
https://github.com/amrgetment/flutter_file_picker/commit/1ded925ad24b3ad958cf5db7b6aa63d7ca4c3c17

And I wonder if here is the right place to ask about migration support?

**Comment by srujzs** [comment]
> And I wonder if here is the right place to ask about migration support?

Sure, one of the goals is to help migrate away from `dart:html`.

> _target.children.clear();

There's some wrapping with lists going on with `children`, but ultimately the implementation points to https://github.com/dart-lang/sdk/blob/c5f876b7aaca65c6bdc6d718cf18d0ee9c335afb/sdk/lib/html/dart2js/html_dart2js.dart#L23276. So the equivalent would be:

```dart
var firstChild = _target.firstChild;
while (firstChild != null) {
  _target.removeChild(firstChild);
  firstChild = _target.firstChild;
}
```

This may not be the fastest (might be faster to remove the children starting from the end) or most idiomatic way, but it's the identical equivalent.

> await reader.onLoad.first;

Use the [events helpers](https://github.com/dart-lang/web/tree/main/lib/src/helpers/events) in the helpers folder e.g.

```dart
await EventStreamProviders.loadEvent.forTarget(reader).first;
```

There's [events.dart](https://github.com/dart-lang/web/blob/3d1b4cbaaf7517cf4f86c8cf8ebe31c67040e08a/lib/src/helpers/events/events.dart#L243) which tries to keep the same syntax as `dart:html` but doesn't have all the events added there yet. Feel free to add a missing member in a PR (like with `onLoad`).

**Comment by amrgetment** [comment]
I will try it in the weekend

**Comment by amrgetment** [comment]
I still need support I tried to build with WASM but I got the following error

```
../lib/_internal/file_picker_web.dart:142:66: Error: Function converted via 'toJS' contains invalid
types in its function signature: 'void Function(*dynamic*)'.
Use one of these valid types instead: JS types from 'dart:js_interop', ExternalDartReference, void,
bool, num, double, int, String, extension types that erase to one of these types, '@staticInterop'
types, 'dart:html' types when compiling to JS, or a type parameter that is a subtype of a valid
non-primitive type.
      window.removeEventListener('focus', cancelledEventListener.toJS);
                                                                 ^
../lib/_internal/file_picker_web.dart:156:64: Error: Function converted via 'toJS' contains invalid
types in its function signature: 'void Function(*dynamic*)'.
Use one of these valid types instead: JS types from 'dart:js_interop', ExternalDartReference, void,
bool, num, double, int, String, extension types that erase to one of these types, '@staticInterop'
types, 'dart:html' types when compiling to JS, or a type parameter that is a subtype of a valid
non-primitive type.
    uploadInput.addEventListener('change', changeEventListener.toJS);
                                                               ^
../lib/_internal/file_picker_web.dart:157:67: Error: Function converted via 'toJS' contains invalid
types in its function signature: 'void Function(*dynamic*)'.
Use one of these valid types instead: JS types from 'dart:js_interop', ExternalDartReference, void,
bool, num, double, int, String, extension types that erase to one of these types, '@staticInterop'
types, 'dart:html' types when compiling to JS, or a type parameter that is a subtype of a valid
non-primitive type.
    uploadInput.addEventListener('cancel', cancelledEventListener.toJS);
                                                                  ^
../lib/_internal/file_picker_web.dart:160:61: Error: Function converted via 'toJS' contains invalid
types in its function signature: 'void Function(*dynamic*)'.
Use one of these valid types instead: JS types from 'dart:js_interop', ExternalDartReference, void,
bool, num, double, int, String, extension types that erase to one of these types, '@staticInterop'
types, 'dart:html' types when compiling to JS, or a type parameter that is a subtype of a valid
non-primitive type.
    window.addEventListener('focus', cancelledEventListener.toJS);
```

My migration

![image](https://github.com/dart-lang/web/assets/149420647/52bc3306-2a9c-4eec-a4a1-9f3b075d0669)

**Comment by ykmnkmi** [comment]
With the new interop, you can't use the `dynamic` type. Add the `Event` type to the `e` argument of the `changeEventListener` function:
```dart
void changeEventListener(Event e) async {
  // ...
}
```

**Comment by amrgetment** [comment]
Thanks builds fine now 😍

**Comment by amrgetment** [comment]
I tried to run the app for testing and I goe the following error:
Error: TypeError: Instance of 'NativeByteBuffer': type 'NativeByteBuffer' is not a subtype of type 'Uint8List?'
for this code
`addPickedFile(file, reader.result as Uint8List?, null, null);`

so how to convert NativeByteBuffer to Uint8List

**Comment by amrgetment** [comment]
I used this conversion and it works fine now
```
          ByteBuffer? byteBuffer = reader.result as ByteBuffer?;
          addPickedFile(file, byteBuffer?.asUint8List(), null, null);

```

**Comment by amrgetment** [comment]
My full PR for the reference 
https://github.com/miguelpruivo/flutter_file_picker/pull/1481

**Comment by amrgetment** [comment]
ok, I will update it, thanks a lot

**Comment by amrgetment** [comment]
I wonder why byteBuffer is not nullable here?
![image](https://github.com/dart-lang/web/assets/149420647/1f9800dd-5571-47d0-99b5-f3a4242e4a02)

**Comment by srujzs** [comment]
Presumably, analysis is smart enough to know that its value is non-nullable? This also gives me a hint:

```dart
void main() {
  int? x = 5;
  x?.isEven;
}
```

If you don't know if `reader.result` is nullable or not, you can downcast to the nullable type instead:

```dart
ByteBuffer? byteBuffer = (reader.result as JSArrayBuffer?)?.toDart;
```

**Comment by amrgetment** [comment]
Thanks
Works fine now, I wonder how to run Flutter with WASM in debugging mode? is it by `--web-renderer skwasm`

**Comment by srujzs** [comment]
dart2wasm doesn't have a debugging mode yet unfortunately.
