### ISSUE TITLE
requestFullscreen and enterFullscreen on HTMLVideoElement

### ISSUE THREAD

**Issue by deepak786** [dart-lang/web#216]
Currently I'm migrating the code to use web package.
I have video element.
```
final videoElement = web.HTMLVideoElement();
```

requestFullscreen and enterFullscreen methods are not available on HTMLVideoElement
```
videoElement.requestFullscreen();
videoElement.enterFullscreen();
```

**Comment by deepak786** [comment]
Similarly exitFullscreen

**Comment by deepak786** [comment]
For now I have used the extension

```
extension on web.HTMLVideoElement {
  external JSPromise requestFullscreen();

  external JSPromise enterFullscreen();
}
```

**Comment by srujzs** [comment]
`requestFullscreen` and `exitFullscreen` should be addressed in https://github.com/dart-lang/web/issues/209, but I'm not sure `enterFullscreen` still exists as part of the spec: https://developer.mozilla.org/en-US/docs/Web/API/Document/exitFullscreen.
