### ISSUE TITLE
Event Handler's Getters and Setters in dom.dart are defined as smallcase. 

### ISSUE THREAD

**Issue by kaljitism** [dart-lang/web#220]
In `lib/src/dom/dom.dart` Event Handlers getters and setters APIs are Small Case Identifiers, they should be converted to Camel Case Identifiers. 

Code Link - https://github.com/dart-lang/web/blob/main/lib/src/dom/dom.dart

For example - 

```
. . . . . . 
 external set onanimationcancel(EventHandler value);
 external EventHandler get ontransitionrun;
 external set ontransitionrun(EventHandler value);
 external EventHandler get ontransitionstart;
 external set ontransitionstart(EventHandler value);
 external EventHandler get ontransitionend;
 external set ontransitionend(EventHandler value);
 external EventHandler get ontransitioncancel;
 external set ontransitioncancel(EventHandler value);
. . . . . 
```

should be renamed to 

```
. . . . . . 
 external set onAnimationCancel(EventHandler value);
 external EventHandler get onTransitionRun;
 external set onTransitionRun(EventHandler value);
 external EventHandler get onTransitionStart;
 external set onTransitionStart(EventHandler value);
 external EventHandler get onTransitionEnd;
 external set onTransitionEnd(EventHandler value);
 external EventHandler get onTransitionCancel;
 external set onTransitionCancel(EventHandler value);
. . . . . 
```

**Comment by kaljitism** [comment]
I have forked the repo and working on it.

**Comment by kaljitism** [comment]
Fixed this in [PR](https://github.com/dart-lang/web/pull/221)

**Comment by ykmnkmi** [comment]
Did you test all these changes?

**Comment by kaljitism** [comment]
@ykmnkmi Since its a typo related fix, I believe it might be a breaking change. Correct me if I am wrong. 

Also, I did not test. how do I do it for these specific changes??  Would I need to write my own tests or the checks that will be done by Github Actions and Reviewers would be fine?

**Comment by ykmnkmi** [comment]
@kaljitism it's not a typo; the current naming for event handlers directly mirrors that of the JavaScript DOM API. At least add JS annotations with proper names:
```dart
@JS('onanimationcancel')
external set onAnimationCancel(EventHandler value);
```

**Comment by kaljitism** [comment]
I see. On it.

**Comment by kevmoo** [comment]
This is by design. We map exactly to what's in the Web IDL.
