### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by jarrodcolburn** [dart-lang/web#225]
Getting broken Links on pages. For example... [Event Extension Type](https://pub.dev/documentation/web/latest/web/Event-extension-type.html)

![image](https://github.com/dart-lang/web/assets/16673615/58d41b50-9907-40fa-882e-f29aadcc0185)

clicking one results in

![image](https://github.com/dart-lang/web/assets/16673615/9366fc1e-499d-4d03-b513-8679431fafde)

Looking at the example [code](https://github.com/dart-lang/web/blob/9d8c802d13b785b1a5b201c4a43605d640841c98/lib/src/dom/dom.dart#L60) Seems to be effecting the links that are defined as methods. Probably a DartDoc thing?

**Comment by kevmoo** [comment]
CC @devoncarew @srujzs – more path parsing fun!

**Comment by srujzs** [comment]
Devon fixed this here: https://github.com/dart-lang/web/commit/2f13cd55f938f71bcd16c831110e3a196967337f

I'm guessing it's because we haven't released a version with this yet that pub.dev isn't showing it?

**Comment by devoncarew** [comment]
It looks like the last major version publish was ~2 months ago (`0.5.0`, https://pub.dev/packages/web/versions/0.5.0, 2/13). I believe last time this was discussed we thought a major release cadence roughly aligned with the sdk releases made sense (or, no more frequently then the sdk releases). So, we may be due for a new major release in the next few weeks?

**Comment by srujzs** [comment]
Yes, I think so too (with an IDL update). I'm planning on getting https://github.com/dart-lang/web/issues/209 and possibly https://github.com/dart-lang/web/issues/57 before that, but the pub documentation should be resolved when the next version is released, so I'll mark this as closed.
