### ISSUE TITLE
Why not just support WASM in dart:html?

### ISSUE THREAD

**Issue by amrgetment** [dart-lang/web#228]
I wonder why not just make dart:html support WASM?
I don’t have all the information about package:web that’s why I asked this question 
I am a fan of WASM and I am waiting for the next Flutter release to get WASM in the stable channel 🤗😍

**Comment by kevmoo** [comment]
It's more like `dart:html` doesn't support Wasm!

We need much stricter type rules to work with WebAssembly. `dart:html` was designed to only work with JavaScript so it bends a LOT of rules that you can get away with in JS, but not with Wasm.

The benefit of `pkg:web`: it's MUCH more up-to-date and it'll be smaller/faster than `dart:html`

**Comment by amrgetment** [comment]
Thanks a lot for the clarification :)

**Comment by amrgetment** [comment]
@kevmoo I found a very wonderful article about my question
**History of JS interop in Dart**
https://medium.com/dartlang/history-of-js-interop-in-dart-98b06991158f
