### ISSUE TITLE
 Error: Type 'JSString' not found.   external JSArray<JSString> get transports;

### ISSUE THREAD

**Issue by shakibhoseen** [dart-lang/web#233]
Invalid depfile: D:\flutter\app\test_lfm_flutter_new\.dart_tool\flutter_build\551dc14c0474116e051f6a952e93f4ab\kernel_snapshot.d
Invalid depfile: D:\flutter\app\test_lfm_flutter_new\.dart_tool\flutter_build\551dc14c0474116e051f6a952e93f4ab\kernel_snapshot.d

/C:/Users/myPc/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.5.1/lib/src/dom/webauthn.dart:647:20: Error: Type 'JSString' not found.
  external JSArray<JSString> get transports;
  
  /C:/Users/bdCalling%20IT/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.16.0/lib/src/firebase_core_web.dart:176:9: Error: The getter 'globalContext' isn't defined for the class 'FirebaseCoreWeb'.
 - 'FirebaseCoreWeb' is from 'package:firebase_core_web/firebase_core_web.dart' ('/C:/Users/bdCalling%20IT/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.16.0/lib/firebase_core_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'globalContext'.
    if (globalContext.getProperty('firebase_core'.toJS) != null) {
        ^^^^^^^^^^^^^
/C:/Users/bdCalling%20IT/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.16.0/lib/src/firebase_core_web.dart:176:51: Error: The getter 'toJS' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'toJS'.
    if (globalContext.getProperty('firebase_core'.toJS) != null) {
                                                  ^^^^
/C:/Users/bdCalling%20IT/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.16.0/lib/src/interop/package_web_tweaks.dart:10:8: Error: Dart library 'dart:js_interop' is not available on this platform.
import 'dart:js_interop';
       ^
/C:/Users/bdCalling%20IT/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.16.0/lib/src/interop/package_web_tweaks.dart:18:4: Error: Couldn't find constructor 'JS'.
  @JS('trustedTypes')
   ^^
/C:/Users/bdCalling%20IT/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.16.0/lib/src/interop/package_web_tweaks.dart:26:4: Error: Couldn't find constructor 'JS'.
  @JS('createScriptURL')
   ^^
/C:/Users/bdCalling%20IT/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.16.0/lib/src/interop/package_web_tweaks.dart:35:4: Error: Couldn't find constructor 'JS'.
  @JS('text')
   ^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs_interop; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34)
#1      asFileUri (package:vm/kernel_front_end.dart:752)
#2      writeDepfile (package:vm/kernel_front_end.dart:892)
  
  i try to 
  
dependency_overrides:
    web: ^0.4.0
    
    but the still problem comes, i switched stable to the beta channel still not solved yet. I use firebase_auth but I see inside the firebase_auth library package by going external_libraries, open pubspec.yaml of that library, I see inside there web: ^0.5.1 available and error comes but why?

**Comment by srujzs** [comment]
Both files definitely have an import to `dart:js_interop`, which should contains all of those symbols, so there's something weird going on. Maybe try clearing your pub cache? Is there a full repro you can share?
