### ISSUE TITLE
gamepad bindings not working

### ISSUE THREAD

**Issue by robertmuth** [dart-lang/web#235]
This new library has them same issue as the old one - as reported here  https://github.com/dart-lang/sdk/issues/33148 in 2018.

The gamepad fields such as buttons and axes are not updated but remain in the frozen state when the Gamepad object was 
instantiated. Maybe these fields need have some notion of "volatile" or maybe they should be exposed via API functions that internally force a "re-lookup" of the fields.

**Comment by srujzs** [comment]
It looks like that's WAI according to the spec (unless I'm missing something): https://w3c.github.io/gamepad/#gamepad-interface

We could add helper functions to force that re-lookup in https://github.com/dart-lang/web/tree/main/lib/src/helpers to make it easier for users. I don't have access to a controller, but if you're willing to contribute, I'm happy to review.

**Comment by robertmuth** [comment]
Looks like you are right. This JS example also creates a new "Gamepad " everytime it polls:

https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API
