### ISSUE TITLE
`MessageChannel` seems to fail to work after migration

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/web#253]
Hi thanks for the framework! When migrating https://github.com/fzyzcjy/flutter_rust_bridge, MessageChannel seems to fail.

(Optional) Background: It was originally used e.g. to communicate between JS main thread and a Web Worker running Rust code compiled to WASM, and I found it not working after migration. Then, I have reduced it and below is a minimal reproducible sample.

Here is a minimal reproducible sample:

Code

<details>

```dart
import 'dart:async';
import 'dart:html' as html;
import 'dart:js_interop' as dart_js_interop;

import 'package:web/web.dart' as web;

Future<void> run_packageweb() async {
  print('run_packageweb start');

  final messageChannel = web.MessageChannel();

  web.EventStreamProvider<web.MessageEvent>('message')
      .forTarget(messageChannel.port1)
      .listen((event) => print('messageChannel.port1 see event ${event.data}'));

  print('Dart call postMessage');
  messageChannel.port2.postMessage(12345.toJS);
}

Future<void> run_darthtml() async {
  print('run_darthtml start');

  final messageChannel = html.MessageChannel();

  html.EventStreamProvider<html.MessageEvent>('message')
      .forTarget(messageChannel.port1)
      .listen((event) => print('messageChannel.port1 see event ${event.data}'));

  print('Dart call postMessage');
  messageChannel.port2.postMessage(12345);
}

Future<void> main() async {
  // await run_packageweb();
  await run_darthtml();

  print('Dart start sleeping');
  await Future.delayed(const Duration(seconds: 1000000));
}
```

</details>

For completeness, here is a text diff for the code:

![image](https://github.com/dart-lang/web/assets/5236035/8b350d36-8a9e-4a8a-a3a7-6f6f2deeab37)

How to execute:
* Copy-paste to, e.g. `test/demo_test.dart`
* Run it once with `await run_packageweb()` uncommented, and by executing `dart test test/demo_test.dart -p chrome`
* Run it again, now comment out `await run_packageweb` and let `await run_darthtml` uncommented

Results:

package:web variant does not receive things:

```
run_packageweb start
Dart call postMessage
Dart start sleeping
```

dart:html variant *does* get the event:

```
run_darthtml start
Dart call postMessage
Dart start sleeping
messageChannel.port1 see event 12345
```

**Comment by srujzs** [comment]
Note that the `dart:html` implementation has some extra code for [`MessagePort.addEventListener`](https://github.com/dart-lang/sdk/blob/e23e032406e2ab41641a5ea16a5f7020e06ff83b/sdk/lib/html/dart2js/html_dart2js.dart#L21653), where it explicitly calls [`start`](https://developer.mozilla.org/en-US/docs/Web/API/MessagePort/start) to start sending the messages. You can do the same by calling `start`:

```dart
  final messageChannel = web.MessageChannel();

  web.EventStreamProvider<web.MessageEvent>('message')
      .forTarget(messageChannel.port1)
      .listen((event) => print('messageChannel.port1 see event ${event.data}'));

  messageChanngel.port1.start();

  print('Dart call postMessage');
  messageChannel.port2.postMessage(12345.toJS);
```

**Comment by fzyzcjy** [comment]
Ah thank you for that!
