### ISSUE TITLE
How to apply CSS classes to HTMLElements?

### ISSUE THREAD

**Issue by r-durao-pvotal** [dart-lang/web#254]
Hello, 

I've got a question regarding migrating from `dart:html` to this package regarding applying CSS classes to elements.

With `dart:html` we could do:

```dart
final myDiv = DivElement()..classes.add('myCssClass');
```

How can we achieve the same with `web`'s `HTMLDivElement` ?

**Comment by ykmnkmi** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add):
```dart
final myDiv = HTMLDivElement()..classList.add('myCssClass');
```

**Comment by r-durao-pvotal** [comment]
Thank you @ykmnkmi
