### ISSUE TITLE
Going FullScreen in iOS 

### ISSUE THREAD

**Issue by raman04-byte** [dart-lang/web#259]
Well, I am using the web and want to go to full screen on the web when click on the button. 

I think it's missing something on the web. 

I know you have to request for the full screen to do full-screen 
Link: https://api.dart.dev/stable/3.4.4/dart-html/Element/requestFullscreen.html

**Comment by raman04-byte** [comment]
Well how can I request full screen on safari

**Comment by srujzs** [comment]
`v0.6.0` (or `1.0.0` if we move to v1) should contain this: https://github.com/dart-lang/web/blob/6b8a46561b82de9b20d77d9ac491844d303ca08f/lib/src/dom/dom.dart#L3211 and should be out soon (I have all the PRs I want in - just need to fix a small issue with updating the web IDL). To unblock yourself, use an extension method:

```dart
extension on Element {
  external JSPromise<JSAny?> requestFullscreen([JSObject options]);
}
```

See https://dart.dev/interop/js-interop/usage#extension-members-on-interop-types.

**Comment by kevmoo** [comment]
Closing out. Will be released soon!

**Comment by ShivanshuKGupta** [comment]
If we want to implement fullscreen anyhow, without using dart:html.
Is there any workaround? maybe using dart:js_interop?

**Comment by srujzs** [comment]
https://github.com/dart-lang/web/issues/259#issuecomment-2189509263 has a workaround using `dart:js_interop` to `requestFullscreen` until v1 is out. Is that what you're looking for?

**Comment by ShivanshuKGupta** [comment]
Thank you so much for this! I didn't realize that the [#259 comment](https://github.com/dart-lang/web/issues/259#issuecomment-2189509263) was actually a workaround. I'm not very familiar with js_interop and thought it was something that would be released soon.

For anyone else who comes across this, here’s the code that worked for me:

```dart
import 'dart:js_interop';

import 'package:web/web.dart';

extension on Element {
  external JSPromise<JSAny?> requestFullscreen([JSObject options]);
}

extension on Document {
  external JSPromise<JSAny?> exitFullscreen([JSObject options]);
}

class FullscreenUtils {
  static Future<void> enterFullscreen() async {
    document.documentElement!.requestFullscreen();
  }

  static void exitFullscreenOnWeb() {
    document.exitFullscreen();
  }
}
```

**Comment by raman04-byte** [comment]
@kevmoo Is the fullScreen available now?

**Comment by kevmoo** [comment]
https://pub.dev/documentation/web/latest/web/Element/requestFullscreen.html ?

**Comment by raman04-byte** [comment]
Thanks for the link
