### ISSUE TITLE
MAC_FF_META missing from KeyCodes

### ISSUE THREAD

**Issue by arnaud-secondlayer** [dart-lang/web#262]
Firefox (Gecko) fires key code 224 (also known as `MAC_FF_META`)  for the meta key on OSX instead of key code 91.
Right now this code is missing from the KeyCodes, where it was declared in the `html` package.

**Comment by srujzs** [comment]
Thanks! Feel free to add a PR to add this to https://github.com/dart-lang/web/blob/6b8a46561b82de9b20d77d9ac491844d303ca08f/lib/src/helpers/enums.dart. Otherwise, we'll likely get to it after releasing v1 as part of a minor release.
