### ISSUE TITLE
API doc links broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/web#274]
If I go here:

https://pub.dev/documentation/web/latest/web/Node-extension-type.html

and click on `appendChild` under `METHODS` on the right, I get a 404 error.

Not sure if this is a general bug with extension types.

**Comment by kevmoo** [comment]
Weird!

https://pub.dev/documentation/web/latest/web/Node/appendChild.html in the
main body
https://pub.dev/documentation/web/web/Node/appendChild.html on the sidebar

**Comment by srawlins** [comment]
Yes very likely a dartdoc error. We can prioritize a fix for this.

**Comment by kevmoo** [comment]
Closing this out. Seems an issue with dartdoc - https://github.com/dart-lang/dartdoc/issues/3828
