### ISSUE TITLE
getElementById returns null even though element was created previously

### ISSUE THREAD

**Issue by phmv** [dart-lang/web#279]
We are using flutter-webrtc package in our project. Inside web implementation of RTCVideoRenderer we call [`initialize()`](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L257) method which creates an HTMLVideoElement() inside it:
```
final element = web.HTMLVideoElement()
        ..autoplay = true
        ..muted = true
        ..controls = false
        ..srcObject = _videoStream
        ..id = _elementIdForVideo
        ..setAttribute('playsinline', 'true');
```
Right after calling `initialize()` we use a setter [`setSrcObject`](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L107) which calls [`findHtmlView()`](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L216) method inside it. The method contains getting an Element by id `final element = web.document.getElementById(_elementIdForVideo);` but the problem is it returns null.
How does it possible and why does it happen?

_File that contains code described above:_ https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart
_Related issue opened in flutter-webrtc repository:_ https://github.com/flutter-webrtc/flutter-webrtc/issues/1649

**Comment by srujzs** [comment]
It looks like you have to add it to the document tree after you create it.

https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById#usage_notes

> Elements not in the document are not searched by getElementById(). When creating an element and assigning it an ID, you have to insert the element into the document tree with [Node.insertBefore()](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore) or a similar method before you can access it with getElementById()

You're also calling `getElementById` before you assign the id, since you're calling `_videoStream` before you assign `id`, so calling `srcObject` after you add the element to the document and give it an id should fix it.

**Comment by phmv** [comment]
@srujzs Thanks for your answer! I have something to discuss.
> It looks like you have to add it to the document tree after you create it.
The constructor `web.HTMLVideoElement()` [creates element in the dom tree](https://github.com/dart-lang/web/blob/v0.5.1/lib/src/dom/html.dart#L1453C3-L1453C60) and i guess inserts it, but looks like either creating the element or [setting the `id`](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L269) attribute doesn't happen synchronously. Because if i put some delay between calling [`initialize()`](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L257) and [`findHtmlView()`](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L216) then getElementById always finds the element.

> You're also calling getElementById before you assign the id, since you're calling _videoStream before you assign id
The line `..srcObject = _videoStream` is setting a value to the element srcObject attribute right after creating. It doesn't call getElementById since it's not the same thing as setter of [`RTCVideoRenderer`](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L107)

**Comment by srujzs** [comment]
> The constructor web.HTMLVideoElement() [creates element in the dom tree](https://github.com/dart-lang/web/blob/v0.5.1/lib/src/dom/html.dart#L1453C3-L1453C60) and i guess inserts it by the [registerViewFactory](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L258) func, but looks like it doesn't happen synchronously. Because if i put some delay (10ms) between calling [initialize()](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L257) and [findHtmlView()](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L216) then getElementById always finds the element.

Yeah, that seems to be the case. It looks like the passed factory is called later in a call to [`PlatformViewManager.renderContent`](https://github.com/flutter/engine/blob/b66893e1fb7ecd467a31b6614a59cf2d05e26552/lib/web_ui/lib/src/engine/platform_views/content_manager.dart#L158) which then appends it to the document.

> The line ..srcObject = _videoStream is setting a value to the element's srcObject attribute right after creating. It doesn't call getElementById since it's not the same thing as [srcObject setter](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/web/rtc_video_renderer_impl.dart#L107) of RTCVideoRenderer`

Ah right, my mistake. That should be fine then.

**Comment by phmv** [comment]
So i am going to close the issue and leave solving it to flutter-webrtc contributors. Thank you for productive discussion, @srujzs
