### ISSUE TITLE
Make constants that have a value in the IDL non-external

### ISSUE THREAD

**Issue by srujzs** [dart-lang/web#285]
A number of APIs have constant values e.g. [`XMLHttpRequest`](https://github.com/dart-lang/web/blob/fd8c320f860ebee92947c54a3d7045bb3e6399de/lib/src/dom/xhr.dart#L94). We currently emit them as `external` values, but we can emit them as Dart members since the values are known in the IDL e.g. [`XMLHttpRequest`](https://github.com/w3c/webref/blob/e92a26a05c4e1772370239ef26b26758db720337/ed/idl/xhr.idl#L39). The only downside here is that we're ignoring what the browser implements, but in practice, I don't expect that to be different from the IDL values. The benefit of doing this is to be able to use these values in a switch-case.

**Comment by kevmoo** [comment]
Didn't we discuss this somewhere else, too?

**Comment by kevmoo** [comment]
I agree!

**Comment by srujzs** [comment]
> Didn't we discuss this somewhere else, too?

Yup! You brought this up somewhere in an external code review but searching my mail led me to no results.
