### ISSUE TITLE
WebGPU generation is missing.

### ISSUE THREAD

**Issue by munrocket** [dart-lang/web#287]
As I understand `webgpu.idl` is supported in `package:web` but it is impossible to use because `navigator.gpu` on page does not exist. Typical WebGPU example in JS starting like this:

```js
const adapter = await navigator.gpu?.requestAdapter();
const device = await adapter?.requestDevice();
if (!device) {
  fail('need a browser that supports WebGPU');
  return;
}

// Get a WebGPU context from the canvas and configure it
const canvas = document.querySelector('canvas');
const context = canvas.getContext('webgpu');
const presentationFormat = navigator.gpu.getPreferredCanvasFormat();
context.configure({
  device,
  format: presentationFormat,
});
```
So this should compile in dart without commented lines.
```dart
import 'package:web/web.dart';
void main() async {
  console.log(window.navigator as dynamic);
  //console.log(window.navigator.gpu as dynamic);
}
```

**Comment by srujzs** [comment]
[gpu](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/gpu) is still experimental alas, and we [avoid emitting such members](https://github.com/dart-lang/web/tree/main/web_generator#compatibility). Supporting this within your own application is still possible through interop though e.g.

```dart
extension on Navigator {
  external GPU get gpu;
}

extension type GPU._(JSObject _) implements JSObject {
  external JSPromise<GPUAdapter> requestAdapter(JSObject options);
  // other members
}

extension type GPUAdapter._(JSObject _) implements JSObject {
  // other members
}
```

**Comment by munrocket** [comment]
Thanks.

**Comment by munrocket** [comment]
I will reopen issue, because webgpu.idl source seems not full. It’s not just missing `navigator.gpu` that can be easily patched.

Actual:
https://github.com/dart-lang/web/blob/3619fd8391b32ddde18a1ca441b288ff3c39f524/web/lib/src/dom/webgpu.dart#L4

Expected (roughly):
https://github.com/gpuweb/types/blob/main/dist/index.d.ts

Expected IDL source:
https://hg.mozilla.org/mozilla-central/file/tip/dom/webidl/WebGPU.webidl

WebGPU is really hot technology and implemented in Chrome Stable and behind the flag in Safari and Firefox.

**Comment by munrocket** [comment]
> Supporting this within your own application is still possible through interop though e.g.

Maybe better to use generator from this package. Too much to write by hand.

**Comment by srujzs** [comment]
Sorry for the late response here, but I'm working on allowing the generator to generate all the bindings through a flag even if we never check them in. While we may not want to include all the bindings in the `web` package, being able to generate all of them allows you to avoid having to write the missing ones by hand at least.

**Comment by srujzs** [comment]
FYI, https://github.com/dart-lang/web/pull/302 has landed. If you check out this repo, and follow the instructions [here](https://github.com/dart-lang/web/blob/main/web_generator/README.md#generate-all-bindings), the generator will generate all the bindings, including WebGPU.

**Comment by munrocket** [comment]
Ty.
