### ISSUE TITLE
How to pass multiple values to a method like [console.log]

### ISSUE THREAD

**Issue by schultek** [dart-lang/web#289]
Many js methods like `console.log` accept any number of values.
https://developer.mozilla.org/en-US/docs/Web/API/console/log_static

However the dart api only has a single `JSAny` parameter.
Is it somehow possible to pass multiple values?

**Comment by ykmnkmi** [comment]
Write your own wrapper:
```dart
import 'dart:js_interop';

@JS('console.log')
external void consoleLog(
  JSAny? arg1, [
  JSAny? arg2,
  JSAny? arg3,
  JSAny? arg4,
  JSAny? arg5,
  JSAny? arg6,
  JSAny? arg7,
  JSAny? arg8,
  JSAny? arg9,
]);

void main() {
  consoleLog(1.toJS, 2.toJS);
}
```

**Comment by ykmnkmi** [comment]
Or using extension:
```dart
import 'dart:js_interop';

import 'package:web/web.dart';

extension on $Console {
  @JS('log')
  external void log2(JSAny? data, JSAny? data2);

  @JS('log')
  external void log3(JSAny? data, JSAny? data2, JSAny? data3);

  // ...
}

void main() {
  console.log2(1.toJS, 2.toJS);
}
```

**Comment by schultek** [comment]
Nice thanks

**Comment by srujzs** [comment]
Thanks @ykmnkmi! Check out the usage docs as well: https://dart.dev/interop/js-interop/usage#extension-members-on-interop-types.

The IDL [exposes this function](https://github.com/w3c/webref/blob/5928ef54cd6f46166cf81006e4b975c1e4ca26bb/ed/idl/console.idl#L14) as a variadic function but Dart doesn't support variadic args so we default to one arg. We could consider generating N (for some fixed N) args instead.
