### ISSUE TITLE
History.back() behaves differently than documentation says.

### ISSUE THREAD

**Issue by busslina** [dart-lang/web#313]
[Docs](https://pub.dev/documentation/web/latest/web/History/back.html) says:
```
The back() method of the History interface causes the browser to move back one page in the session history.

It has the same effect as calling . If there is no previous page, this method call does nothing.

This method is . Add a listener for the Window.popstate_event event in order to determine when the navigation has completed.
```

I'm testing the case where there isn't previous page and it is doing something: moving to root path.

Tested on Edge and Chrome.

Demo:

https://github.com/user-attachments/assets/a31abb93-15e7-4167-a19c-15bbd65158aa

**Comment by srujzs** [comment]
Looks like the docs are semi-malformed (missing `asynchronous` after "This method is "), but the MDN [docs](https://developer.mozilla.org/en-US/docs/Web/API/History/back) don't contain much more information. Is there a small repro you can share here? My only guess is that `history` is being modified somehow within the code.

**Comment by busslina** [comment]
> Is there a small repro you can share here?

Not easy because I'm developping my own Flutter routing lib.

But I'm just calling that method:
```dart
@override
  SynchronousFuture<NavigationResult> flashBack() {
    if (!kIsWeb) {
      throw ('Only implemented for web');
    }

    web.window.history.back();
    return SynchronousFuture(const NavigationResult.success());
  }
```

**Comment by busslina** [comment]
And yeah, seems the doc error came from MDN.

**Comment by srujzs** [comment]
> Not easy because I'm developping my own Flutter routing lib.

Gotcha. One option is to explore the `history` object before calling `back`, like determining if `history.length` is actually 1.

**Comment by busslina** [comment]
Thanks, I was worried to use that API as I tried to use the `state` object and it was a pain. But using `length` make it easy:
```dart
bool get canFlashBack => web.window.history.length >= 2;
```

**Comment by srujzs** [comment]
Great! I'm going to go ahead and close this for now since there's nothing actionable on `package:web`.

**Comment by busslina** [comment]
Thanks!
