### ISSUE TITLE
Issue: Build Fails Due to Errors in Web Package 

### ISSUE THREAD

**Issue by goutham-murali-03** [dart-lang/web#320]
I’m encountering build failures pointing to the web package. These errors are surfacing from official package code in web, which is a **transitive dependency** in my project and not used directly. Happens on both iOS and Android

1. Deleted pubspec.lock
2. Ran dart pub cache clean
3. Rebuilt the project
4. Tried overriding the web dependency to lower versions (0.4.0, 0.5.0 ..., 1.1.0)

Flutter version - 3.24.3
<img width="1167" alt="Screenshot 2024-11-05 at 11 05 25 AM" src="https://github.com/user-attachments/assets/be78c4f4-b78c-4cc1-82c3-dea4981b0ebc">

PS: Project was building succesfully till last week.

**Comment by Shabeebcp** [comment]
Then , How do you Fixed it ?
