### ISSUE TITLE
JSPromise interop seems to be broken for some JS types

### ISSUE THREAD

**Issue by maks** [dart-lang/web#322]
I am trying to implement support for WebSerial on top of the web package myself because the web package does not support non standards track API, of which [WebSerial is one](https://wicg.github.io/serial/#sotd).

In doing so, I need to have a function that returns a JSPromise:
```
external JSPromise<JSSerialPort> requestPort();
```
but this appears to be broken with the current JS interop in Flutter 3.24.1 as I get a error thrown when I try to access a property of the returned object after awaiting the JSPromise:
```
final port = await getWebSerial().toDart;
print("got serial port readable: ${port.readable}");
```

```
Connecting to VM Service at ws://127.0.0.1:41369/11bElE0uUsY=/ws
Connected to the VM Service.
JS port is:[object SerialPort]
DartError: TypeError: null: type 'Null' is not a subtype of type 'Object'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
errors.dart:296
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1483:3                         _asObject
rti.dart:1483
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 81:5                 getProperty
js_util_patch.dart:81
packages/flutter_webserial/main.dart 15:45                                   chooseSerialDevice
main.dart:15
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
```

To be sure of this, I am calling a function on the JS side which logs what its returning:
```
globalThis.getWebSerial = async function () {
    const port = await navigator.serial.requestPort();
    console.log("JS port is:" + port, port)
    return port;
}
```
and the logging shows me its a valid object and NOT null.

I have basic [Flutter app demoing the issue here](https://github.com/maks/flutter_webserial) in the latest commit fcdbcf4d64c2ca94be035956984bf37f9f1349a0

**Comment by denniskaselow** [comment]
`readable` is nullable, the exception happens because it's `JSAny` in your code but the initial value of `readable` is `null`:

https://wicg.github.io/serial/#dom-serialport

Internal slot | Initial value | Description (non-normative)
-- | -- | --
readable | null | A ReadableStream that receives data from the port

Though it does seem strange that it's not nullable in the IDL: `readonly attribute ReadableStream readable;`

If I change the line `external JSAny readable;` to `external JSAny? readable;` it works:
```
JS port is:[object SerialPort] SerialPort {onconnect: null, ondisconnect: null, readable: null, writable: null, connected: true}
js_primitives.dart:28 got serial port readable: null
```

I used this code, without flutter but with your js:
```dart
import 'dart:js_interop';

import 'package:web/web.dart';

void main() async {
  document.body!.onClick.listen((data) async {
    final port = await getWebSerial().toDart;
    print("got serial port readable: ${port.readable}");
  });
}

@JS()
external JSPromise<JSSerialPort> getWebSerial();

extension type JSSerialPort._(JSObject _) implements JSObject {
  external JSAny? readable;
}
```

**Comment by maks** [comment]
@denniskaselow  thanks so much for spotting my mistake! 🙏🏻   I was completely focused on the JSSerialPort class itself and didnt notice the nullability needed for the readable property that was staring me right in the face in my JS debug logging! 
It all works fine now and I'm moving to create a simple package for WebSerial to make this easier for anyone in future who wants to use it from Dart.
