### ISSUE TITLE
type '({LegacyJavaScriptObject buffer})' is not a subtype of type 'JSObject'

### ISSUE THREAD

**Issue by munrocket** [dart-lang/web#324]
I am getting strange error:
```
DartError: TypeError: Record (buffer: Instance of 'LegacyJavaScriptObject'): type '({LegacyJavaScriptObject buffer})' is not a subtype of type 'JSObject'
```
When I am run this code
```dart
entries: [
  GPUBindGroupEntry(
    binding: 0,
    resource: sampler,
  ),
  GPUBindGroupEntry(
    binding: 1,
    resource: (
      buffer: blurParamsBuffer <-- Error
    ) as GPUBindingResource
  ),
] as JSArray<GPUBindGroupEntry>,
```
As you can see resource type can be different, that is why it's just JSObject in definition
```dart
typedef GPUBindingResource = JSObject;

extension type GPUBindGroupEntry._(JSObject _) implements JSObject {
  external factory GPUBindGroupEntry({
    required GPUIndex32 binding,
    required GPUBindingResource resource,
  });

  external GPUIndex32 get binding;
  external set binding(GPUIndex32 value);
  external GPUBindingResource get resource;
  external set resource(GPUBindingResource value);
}
```
But this cause error. My bindings from SDK 3.6, but version of SDK 3.5.4 on "macos_x64".

Source: compute example [from repo](https://github.com/munrocket/webgpu-interop).

**Comment by kevmoo** [comment]
Are you using `dart:html` or similar? I believe that's why you're seeing the Legacy object.

CC @srujzs

**Comment by srujzs** [comment]
The error is correct, you're casting a record (which itself contains a `LegacyJavaScriptObject` but is not one) to a `JSObject`:

```dart
resource: (buffer: blurParamsBuffer) as GPUBindingResource
```

You likely want another dictionary type for this type e.g.

```dart
extension type GPUBindingResource._(JSObject _) implements JSObject {
  external factory GPUBindingResource({
    required GPUBuffer buffer,
  });
}
...
resource: GPUBindingResource(buffer: blurParamsBuffer)
```

**Comment by munrocket** [comment]
Thanks, I was desperate yesterday. By the way better to hide all typed lists in `webglX.dart` or add to them additional methods. This types too basic to not be covered. Now they declared like that
```dart
typedef Float32List = JSObject;
```
But in code when you using it, you [forced to hide it](https://github.com/munrocket/webgpu-interop/blob/c638e6f5164b8552a9b82fc2203b5f3051a3684f/example/cube/main.dart#L4C1-L4C48)
```dart
import 'dart:js_interop';
import 'package:web/web.dart' hide Float32List, Uint32List;
```
As I understand no `dart:web_gl` user is migrated to `package:web` yet.

**Comment by denniskaselow** [comment]
I'm doing [the same thing](https://github.com/KayZGames/gamedev_helpers/blob/c3e3a99ea137eb81dc3ed8787d45a4d44cb7adbe/lib/src/dartemis/systems/rendering_webgl.dart#L8). Those conflicts are a bit annoying as you can't really do anything with the Float32List from `package:web`.

But there is an open issue for this: https://github.com/dart-lang/web/issues/58

**Comment by srujzs** [comment]
Yup, there's an open issue (although it'd be a breaking change).

Another option is to always import it with a prefix, but that's going to be quite verbose when you're using lots of types.
