### ISSUE TITLE
The second argument for Worker.postMessage could use a better name

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/web#63]
The static interop definition for the `Worker` class defines the `postMessage` function as such:

```
  external JSVoid postMessage(
    JSAny? message, [
    JSAny? optionsOrTransfer,
  ]);
```

However, postMessage does not accept any 'options' as the second argument, only a Transferrable Object (or null, if not applicable). Thus the naming `optionsOrTransfer` is misleading. `transfer` would be a better name. (which conveniently is also the name of the argument itself)

See https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage#parameters

**Comment by kevmoo** [comment]
Names are just picked up from the IDLs. We likely will only do very targeted diffs (if any) from these just to make maintenance more straight forward.

It might be work filing an issue w/ the IDL sources, though!

**Comment by navaronbracke** [comment]
@kevmoo Mea culpa, I should have had a look at the W3C spec first. It does list the options as a second invocation type here 

https://www.w3.org/TR/service-workers/#service-worker-postmessage-options

So the MDN docs which are out of date.

**Comment by kevmoo** [comment]
No worries, yo. Good instincts!
