### ISSUE TITLE
Refactor use of typeofEquals and instanceof and remove isInstanceOfDomType

### ISSUE THREAD

**Issue by srujzs** [dart-lang/web#77]
`dart:js_interop` will have the following changes with https://dart-review.googlesource.com/c/sdk/+/326691:

 - `typeofEquals` takes a `String` and returns `bool`
 - `instanceof` returns a `bool`
 - `instanceOfString` is added to check `instanceof` with types that are available in the global context. `isInstanceOfDomType` does the same thing and can be removed.

This will require publishing a new version and updating the minimum SDK.

**Comment by kevmoo** [comment]
Are the changes to `dart:js_interop` breaking? Do we have the changelog updated?

**Comment by srujzs** [comment]
Yes, and yes in the above CL once it lands. It makes sense to have these go in before 3.2 releases before more packages migrate.
